#!/usr/bin/env bash
# Install autostart: open Chromium in kiosk mode pointing at the Frameflow
# display page, survive reboots, and recover from crashes.
#
# Usage (on the Pi, in the user session — NOT as root):
#   bash scripts/setup-kiosk.sh
#
# Env overrides:
#   FRAMEFLOW_URL   default: https://anonymchat.digital:675/
#   AUTOSTART_DIR   default: ~/.config/autostart
set -euo pipefail

if [[ $EUID -eq 0 ]]; then
  echo "Run this as your normal user (NOT sudo)." >&2
  exit 1
fi

FRAMEFLOW_URL="${FRAMEFLOW_URL:-https://anonymchat.digital/frame}"
AUTOSTART_DIR="${AUTOSTART_DIR:-$HOME/.config/autostart}"

# Detect the browser binary.
BROWSER=""
for cmd in chromium-browser chromium google-chrome; do
  if command -v "$cmd" >/dev/null 2>&1; then BROWSER="$cmd"; break; fi
done
if [[ -z "$BROWSER" ]]; then
  echo "Installing chromium-browser…"
  sudo apt-get update -y
  sudo apt-get install -y --no-install-recommends chromium-browser unclutter xdotool
  BROWSER="chromium-browser"
fi

# Also install unclutter (hides the mouse cursor) — nice-to-have.
sudo apt-get install -y --no-install-recommends unclutter 2>/dev/null || true

KIOSK_SCRIPT="$HOME/.local/bin/frameflow-kiosk.sh"
mkdir -p "$(dirname "$KIOSK_SCRIPT")"

cat >"$KIOSK_SCRIPT" <<KIOSK
#!/usr/bin/env bash
# Auto-generated by setup-kiosk.sh — edit this file to change the URL.
URL="$FRAMEFLOW_URL"

# Disable screen blanking / energy saving.
xset s off || true
xset -dpms || true
xset s noblank || true

# Hide the mouse cursor after 1 second of inactivity.
(unclutter -idle 1 -root &) >/dev/null 2>&1 || true

# Clean up any previous Chromium crash flags so we don't see the yellow banner.
SESSION_FILE="\$HOME/.config/chromium/Default/Preferences"
if [[ -f "\$SESSION_FILE" ]]; then
  sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' "\$SESSION_FILE" || true
  sed -i 's/"exit_type":"[^"]*"/"exit_type":"Normal"/' "\$SESSION_FILE" || true
fi

# Run Chromium in kiosk mode. If it crashes, wait a bit and restart.
while true; do
  $BROWSER \\
    --kiosk \\
    --noerrdialogs \\
    --disable-infobars \\
    --disable-session-crashed-bubble \\
    --disable-features=TranslateUI \\
    --overscroll-history-navigation=0 \\
    --check-for-update-interval=31536000 \\
    --ignore-certificate-errors \\
    --start-maximized \\
    --app="\$URL" \\
    || true
  sleep 5
done
KIOSK
chmod +x "$KIOSK_SCRIPT"
echo "Wrote $KIOSK_SCRIPT"

# Desktop autostart entry (works on LXDE/LXQt/XFCE/GNOME when the user logs in
# automatically on boot).
mkdir -p "$AUTOSTART_DIR"
cat >"$AUTOSTART_DIR/frameflow-kiosk.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Frameflow Kiosk
Exec=$KIOSK_SCRIPT
X-GNOME-Autostart-enabled=true
Terminal=false
NoDisplay=false
Comment=Start Frameflow in kiosk mode
EOF
echo "Wrote $AUTOSTART_DIR/frameflow-kiosk.desktop"

echo ""
echo "✅ Kiosk autostart installed."
echo "    URL:    $FRAMEFLOW_URL"
echo "    Script: $KIOSK_SCRIPT"
echo ""
echo "IMPORTANT:  your Pi must auto-login into the desktop.  On Raspberry Pi OS:"
echo "    sudo raspi-config  →  1 System Options → S5 Boot / Auto Login"
echo "                       →  Desktop Autologin"
echo ""
echo "Reboot to test:  sudo reboot"
